{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_debug-1.0.aar",
          "url": "webview_flutter_android_debug-1.0.aar",
          "size": 145174,
          "sha512": "75afda8b132269d4ece9b8294da25b8591710ba42198db45a4506dd943b2da0fcc3a03d335ed9e0ef79ce8304e03dfc4c2aa78aeebc7456e82639c25d9cb6d54",
          "sha256": "a8b866978ffc1cf41e5def16cfc68a68d6cd3e8706cd03bdd0ac72780980e3b7",
          "sha1": "e8fcfc3d042f1dbcb2f22283f26a69d63bc64e32",
          "md5": "a36168c850a5c3386ad981ba33282b36"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_debug-1.0.aar",
          "url": "webview_flutter_android_debug-1.0.aar",
          "size": 145174,
          "sha512": "75afda8b132269d4ece9b8294da25b8591710ba42198db45a4506dd943b2da0fcc3a03d335ed9e0ef79ce8304e03dfc4c2aa78aeebc7456e82639c25d9cb6d54",
          "sha256": "a8b866978ffc1cf41e5def16cfc68a68d6cd3e8706cd03bdd0ac72780980e3b7",
          "sha1": "e8fcfc3d042f1dbcb2f22283f26a69d63bc64e32",
          "md5": "a36168c850a5c3386ad981ba33282b36"
        }
      ]
    }
  ]
}
