{
  "formatVersion": "1.1",
  "component": {
    "group": "appmire.be.flutterjailbreakdetection",
    "module": "flutter_jailbreak_detection_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_jailbreak_detection_debug-1.0.aar",
          "url": "flutter_jailbreak_detection_debug-1.0.aar",
          "size": 5227,
          "sha512": "9d9e7c413625db950ed790b690df80fec488097310b291187f566d706106b5e4b35195456530d73bceb2867182c31886b56b68efd538633e8261422a02872b5e",
          "sha256": "b7331175746e3caf9aad97d2867358d589ad9065ae242c802f9d14e3c07b600b",
          "sha1": "15eb1025e3e9acca38da4ccdd8a22250028b18b5",
          "md5": "8b0ebeb51919cc5fd7fbd4d17b95373b"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.github.scottyab",
          "module": "rootbeer",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_jailbreak_detection_debug-1.0.aar",
          "url": "flutter_jailbreak_detection_debug-1.0.aar",
          "size": 5227,
          "sha512": "9d9e7c413625db950ed790b690df80fec488097310b291187f566d706106b5e4b35195456530d73bceb2867182c31886b56b68efd538633e8261422a02872b5e",
          "sha256": "b7331175746e3caf9aad97d2867358d589ad9065ae242c802f9d14e3c07b600b",
          "sha1": "15eb1025e3e9acca38da4ccdd8a22250028b18b5",
          "md5": "8b0ebeb51919cc5fd7fbd4d17b95373b"
        }
      ]
    }
  ]
}
