{
  "formatVersion": "1.1",
  "component": {
    "group": "com.syncfusion.flutter.pdfviewer",
    "module": "syncfusion_flutter_pdfviewer_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "syncfusion_flutter_pdfviewer_debug-1.0.aar",
          "url": "syncfusion_flutter_pdfviewer_debug-1.0.aar",
          "size": 10515,
          "sha512": "d25848459443dae741cea4d9239b72413e78d7bd26df900b93553538fa2c4b889000a21a76517e65ead76928619dd3e7e85ffdf10c8b42f9ad77cfe341f3f5e3",
          "sha256": "a8bc2c1fc516b23f31d96d011c4634f38d3584b973334a33b8953672f68ceeac",
          "sha1": "37f321cdf07944c093fcd6bc9edb0960b1dde5b1",
          "md5": "d2fae82f0ecf3716f86d4f62ef6c2f71"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "syncfusion_flutter_pdfviewer_debug-1.0.aar",
          "url": "syncfusion_flutter_pdfviewer_debug-1.0.aar",
          "size": 10515,
          "sha512": "d25848459443dae741cea4d9239b72413e78d7bd26df900b93553538fa2c4b889000a21a76517e65ead76928619dd3e7e85ffdf10c8b42f9ad77cfe341f3f5e3",
          "sha256": "a8bc2c1fc516b23f31d96d011c4634f38d3584b973334a33b8953672f68ceeac",
          "sha1": "37f321cdf07944c093fcd6bc9edb0960b1dde5b1",
          "md5": "d2fae82f0ecf3716f86d4f62ef6c2f71"
        }
      ]
    }
  ]
}
