{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-1.0.aar",
          "url": "webview_flutter_android_release-1.0.aar",
          "size": 136836,
          "sha512": "47a7200140e4c4b0b766f133b39a042317990daa5107233cc0e04ec5ce76cd704f038e3039acafc856c2e478e7d372b2091d50c0d2b8b82f00f9064ce2535e8b",
          "sha256": "fbcf7a5ef7c00dc6d9cdf7a6d27ec32ea8ed080117cae452e6d6fd3ef8f0030d",
          "sha1": "d817c8024b3aa20d1217f2a358fe68c73abe9fb3",
          "md5": "7cfb3aa217e6dd9e9d42c01da3087c9c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-1.0.aar",
          "url": "webview_flutter_android_release-1.0.aar",
          "size": 136836,
          "sha512": "47a7200140e4c4b0b766f133b39a042317990daa5107233cc0e04ec5ce76cd704f038e3039acafc856c2e478e7d372b2091d50c0d2b8b82f00f9064ce2535e8b",
          "sha256": "fbcf7a5ef7c00dc6d9cdf7a6d27ec32ea8ed080117cae452e6d6fd3ef8f0030d",
          "sha1": "d817c8024b3aa20d1217f2a358fe68c73abe9fb3",
          "md5": "7cfb3aa217e6dd9e9d42c01da3087c9c"
        }
      ]
    }
  ]
}
