{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_profile-1.0.aar",
          "url": "permission_handler_android_profile-1.0.aar",
          "size": 28685,
          "sha512": "a96b928eec9411695b7ec0762c38b55b5a85fb5264e0227380e662c56c5e22cec8cde46b1d386e041a419a2e6b287337105dd4b814f57a272126199d89ceedc6",
          "sha256": "72621f5248e6546266b1e9bbb757090688e3531ecad7ed151e32f382f316c314",
          "sha1": "d4de9444a0ae087ce4f726305afb3a124d3fd8c3",
          "md5": "e884f678562bde27d9ab3f2298adf67f"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_profile-1.0.aar",
          "url": "permission_handler_android_profile-1.0.aar",
          "size": 28685,
          "sha512": "a96b928eec9411695b7ec0762c38b55b5a85fb5264e0227380e662c56c5e22cec8cde46b1d386e041a419a2e6b287337105dd4b814f57a272126199d89ceedc6",
          "sha256": "72621f5248e6546266b1e9bbb757090688e3531ecad7ed151e32f382f316c314",
          "sha1": "d4de9444a0ae087ce4f726305afb3a124d3fd8c3",
          "md5": "e884f678562bde27d9ab3f2298adf67f"
        }
      ]
    }
  ]
}
