{
  "formatVersion": "1.1",
  "component": {
    "group": "com.syncfusion.flutter.pdfviewer",
    "module": "syncfusion_flutter_pdfviewer_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "syncfusion_flutter_pdfviewer_release-1.0.aar",
          "url": "syncfusion_flutter_pdfviewer_release-1.0.aar",
          "size": 10128,
          "sha512": "8539e6f9750ba07fa3b70930d244e795149cef5ab36df2483263e20db2b854c6ede0b9150be9d51b9816a6229b8a8193c8404bba57084d304caafcb75ac498c6",
          "sha256": "b107b4af3c59339f85027db4085a8a47958186059e9a4cc08c61b0fa756fab67",
          "sha1": "4842e821dabb30065cc3d85106c14e94479d42f4",
          "md5": "20c3050c1d0226318f67c0b4ced7e68b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "syncfusion_flutter_pdfviewer_release-1.0.aar",
          "url": "syncfusion_flutter_pdfviewer_release-1.0.aar",
          "size": 10128,
          "sha512": "8539e6f9750ba07fa3b70930d244e795149cef5ab36df2483263e20db2b854c6ede0b9150be9d51b9816a6229b8a8193c8404bba57084d304caafcb75ac498c6",
          "sha256": "b107b4af3c59339f85027db4085a8a47958186059e9a4cc08c61b0fa756fab67",
          "sha1": "4842e821dabb30065cc3d85106c14e94479d42f4",
          "md5": "20c3050c1d0226318f67c0b4ced7e68b"
        }
      ]
    }
  ]
}
