{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.deviceinfo",
    "module": "device_info_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_profile-1.0.aar",
          "url": "device_info_profile-1.0.aar",
          "size": 7931,
          "sha512": "55a6597fc88c4c781d3df05ad1f683a024cf78fc180b1a01a1e2a7d744ede6f5faea28c1bca7ccd1ad3017d5bb8e03c46ec18e3a5f3eba5e4847013e78f8459c",
          "sha256": "f3fcc3acd4dae5853dbb06da56603006b88c41edbe197b2c16fba20b28cc1685",
          "sha1": "94586b1a2ccfdb160560af020131ad9cb7f8fbf1",
          "md5": "aa8e0bfef935c41472d3ddb51faa4b42"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_profile-1.0.aar",
          "url": "device_info_profile-1.0.aar",
          "size": 7931,
          "sha512": "55a6597fc88c4c781d3df05ad1f683a024cf78fc180b1a01a1e2a7d744ede6f5faea28c1bca7ccd1ad3017d5bb8e03c46ec18e3a5f3eba5e4847013e78f8459c",
          "sha256": "f3fcc3acd4dae5853dbb06da56603006b88c41edbe197b2c16fba20b28cc1685",
          "sha1": "94586b1a2ccfdb160560af020131ad9cb7f8fbf1",
          "md5": "aa8e0bfef935c41472d3ddb51faa4b42"
        }
      ]
    }
  ]
}
