{
  "formatVersion": "1.1",
  "component": {
    "group": "com.it_nomads.fluttersecurestorage",
    "module": "flutter_secure_storage_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_profile-1.0.aar",
          "url": "flutter_secure_storage_profile-1.0.aar",
          "size": 26673,
          "sha512": "7b1d72361acba9197205b74ebf6988efd1d94ab21efcaeb294ef4805abf002ab4bc66bd475beae92a5385352198127704867aa1767f9cb28a64ec94684c4c85f",
          "sha256": "26a9148e3a70a6fba804501f8f8df9bea6543c317d83bbfc23b11ace65afaed2",
          "sha1": "cd8981c663d268f44d35416b154e4b07c52f87c6",
          "md5": "3e0227bcbab9027e5202a1dedb05f858"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_profile-1.0.aar",
          "url": "flutter_secure_storage_profile-1.0.aar",
          "size": 26673,
          "sha512": "7b1d72361acba9197205b74ebf6988efd1d94ab21efcaeb294ef4805abf002ab4bc66bd475beae92a5385352198127704867aa1767f9cb28a64ec94684c4c85f",
          "sha256": "26a9148e3a70a6fba804501f8f8df9bea6543c317d83bbfc23b11ace65afaed2",
          "sha1": "cd8981c663d268f44d35416b154e4b07c52f87c6",
          "md5": "3e0227bcbab9027e5202a1dedb05f858"
        }
      ]
    }
  ]
}
