{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.deviceinfo",
    "module": "device_info_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_debug-1.0.aar",
          "url": "device_info_debug-1.0.aar",
          "size": 8224,
          "sha512": "aeb0f13ccedf37a3596b3e58ba8edc1c634638d0de634b41c6937fba7a7a17fd61a5c7ffda96b97e5870173b43359f409eff2691c8bab10f5840b854e600afa5",
          "sha256": "ba5dfe50a7d5ac0f7824139cd7c4e2e8da1931d8f95e21ceead39610e7c643ec",
          "sha1": "a249ca0263e95ad749254e748f5d49e6a841f747",
          "md5": "434135e75b4a150f75a8e173a6de6caf"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_debug-1.0.aar",
          "url": "device_info_debug-1.0.aar",
          "size": 8224,
          "sha512": "aeb0f13ccedf37a3596b3e58ba8edc1c634638d0de634b41c6937fba7a7a17fd61a5c7ffda96b97e5870173b43359f409eff2691c8bab10f5840b854e600afa5",
          "sha256": "ba5dfe50a7d5ac0f7824139cd7c4e2e8da1931d8f95e21ceead39610e7c643ec",
          "sha1": "a249ca0263e95ad749254e748f5d49e6a841f747",
          "md5": "434135e75b4a150f75a8e173a6de6caf"
        }
      ]
    }
  ]
}
