{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.localauth",
    "module": "local_auth_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android_profile-1.0.aar",
          "url": "local_auth_android_profile-1.0.aar",
          "size": 40481,
          "sha512": "d11b213de3dd01310c06cde574ae8ff0627f00b8d22bbd1279ef64d97dfb5f53d713f579be293c22a9025f41efe5f5cbcc4a981ca3fba21a0219c4b893e3c81e",
          "sha256": "52edb27918988e3a60fcef0ff00ac14ddefb47d946a3d0bf032036d2dadb1284",
          "sha1": "7dc5e2c477de919d80273b0547f1ea9bb8e1e5c4",
          "md5": "8f7c11c1482ec1eacc3c77a88d253d6c"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.10"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "local_auth_android_profile-1.0.aar",
          "url": "local_auth_android_profile-1.0.aar",
          "size": 40481,
          "sha512": "d11b213de3dd01310c06cde574ae8ff0627f00b8d22bbd1279ef64d97dfb5f53d713f579be293c22a9025f41efe5f5cbcc4a981ca3fba21a0219c4b893e3c81e",
          "sha256": "52edb27918988e3a60fcef0ff00ac14ddefb47d946a3d0bf032036d2dadb1284",
          "sha1": "7dc5e2c477de919d80273b0547f1ea9bb8e1e5c4",
          "md5": "8f7c11c1482ec1eacc3c77a88d253d6c"
        }
      ]
    }
  ]
}
