{
  "formatVersion": "1.1",
  "component": {
    "group": "appmire.be.flutterjailbreakdetection",
    "module": "flutter_jailbreak_detection_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_jailbreak_detection_profile-1.0.aar",
          "url": "flutter_jailbreak_detection_profile-1.0.aar",
          "size": 5062,
          "sha512": "7305aa9a68e94d12f5475514f922993a882c6ad4f5b61211c981dacd057834bcc51c1660bb99d87289d8e3824e2c5426506e9138e6c7d61a861776d397c309dd",
          "sha256": "7c964af463389d682e42ff0a3a1925abd7483bdd9c2293296ef11180a0eb8dfa",
          "sha1": "0277963916a2d9af58ed3ca45c1488398d7e9f32",
          "md5": "12d6f911ef11f990e5a548b9593c4dde"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.github.scottyab",
          "module": "rootbeer",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_jailbreak_detection_profile-1.0.aar",
          "url": "flutter_jailbreak_detection_profile-1.0.aar",
          "size": 5062,
          "sha512": "7305aa9a68e94d12f5475514f922993a882c6ad4f5b61211c981dacd057834bcc51c1660bb99d87289d8e3824e2c5426506e9138e6c7d61a861776d397c309dd",
          "sha256": "7c964af463389d682e42ff0a3a1925abd7483bdd9c2293296ef11180a0eb8dfa",
          "sha1": "0277963916a2d9af58ed3ca45c1488398d7e9f32",
          "md5": "12d6f911ef11f990e5a548b9593c4dde"
        }
      ]
    }
  ]
}
