{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-1.0.aar",
          "url": "permission_handler_android_release-1.0.aar",
          "size": 28688,
          "sha512": "ca878a93f71cba828c55046efa1c3d90fe0060584075ea9667069265149ce088269c4b840eb785958d433b620edd5d63fa0f5f0cd820add7d7bed379fdd2ccd1",
          "sha256": "f8ef645d95501bb5dc2b281a58561ced9115c452a442f5c7bbff3d318670fa15",
          "sha1": "ca005a55e3262a948103a598d47d80e725041a71",
          "md5": "4f68d7dcc315bc005127b0da3230350f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-1.0.aar",
          "url": "permission_handler_android_release-1.0.aar",
          "size": 28688,
          "sha512": "ca878a93f71cba828c55046efa1c3d90fe0060584075ea9667069265149ce088269c4b840eb785958d433b620edd5d63fa0f5f0cd820add7d7bed379fdd2ccd1",
          "sha256": "f8ef645d95501bb5dc2b281a58561ced9115c452a442f5c7bbff3d318670fa15",
          "sha1": "ca005a55e3262a948103a598d47d80e725041a71",
          "md5": "4f68d7dcc315bc005127b0da3230350f"
        }
      ]
    }
  ]
}
