{
  "formatVersion": "1.1",
  "component": {
    "group": "com.crazecoder.openfile",
    "module": "open_file_safe_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        }
      ],
      "files": [
        {
          "name": "open_file_safe_profile-1.0.aar",
          "url": "open_file_safe_profile-1.0.aar",
          "size": 13890,
          "sha512": "2a7c71689d9eb7c64f38d551a617692239103662ae6096f329f758e82f97536d52460f20f01d72f64a5d8fff0230164b9f03ac5e17e90db79da4494db2ee9a71",
          "sha256": "8e56d599394da062c356b4026813080b3a2d6d2d3e4d34b66f996d654db90bfe",
          "sha1": "64f6857fecb0ac75a1c78a0342bfb22d0b565f6c",
          "md5": "014ae0eb1fb9bf03645111929acaddc3"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-0545f8705df301877d787107bac1a6e9fc9ee1ad"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "open_file_safe_profile-1.0.aar",
          "url": "open_file_safe_profile-1.0.aar",
          "size": 13890,
          "sha512": "2a7c71689d9eb7c64f38d551a617692239103662ae6096f329f758e82f97536d52460f20f01d72f64a5d8fff0230164b9f03ac5e17e90db79da4494db2ee9a71",
          "sha256": "8e56d599394da062c356b4026813080b3a2d6d2d3e4d34b66f996d654db90bfe",
          "sha1": "64f6857fecb0ac75a1c78a0342bfb22d0b565f6c",
          "md5": "014ae0eb1fb9bf03645111929acaddc3"
        }
      ]
    }
  ]
}
